"""--dry-run support: generate an equivalent PySCF Python script.

The generated script is the teaching bridge between pyscf-cli and PySCF
itself: students first run the CLI, then inspect what it does, then start
editing the script.  Scripts cover the *main* calculation path; exotic
flags (--mom, --pes, decompositions) are noted as not included so the
output never lies about what it reproduces.
"""

from __future__ import annotations

HEADER = '''#!/usr/bin/env python3
"""Equivalent PySCF script generated by pyscf-cli --dry-run.

Run it with:  python3 this_script.py
Learn more:   https://pyscf.org/
"""
'''


def _imports(args, extra=()):
    theory = getattr(args, "theory", "scf")
    mods = ["gto"]
    if theory == "dft":
        mods.append("dft")
    else:
        mods.append("scf")
    if theory == "mp2":
        mods.append("mp")
    elif theory in ("ccsd", "ccsd_t"):
        mods.append("cc")
    return f"from pyscf import {', '.join(mods)}" + (
        "\n" + "\n".join(extra) if extra else ""
    )


def _mol_block(args):
    atom_lines = "\n".join(
        f"{e:2s} {x:14.8f} {y:14.8f} {z:14.8f}" for e, x, y, z in args.atoms
    )
    return f'''mol = gto.M(
    atom="""
{atom_lines}
""",
    basis="{args.basis}",
    charge={args.charge},
    spin={args.spin},  # 2S = number of unpaired electrons
    unit="{args.unit}",
)'''


def _reference_block(args):
    theory = getattr(args, "theory", "scf")
    if theory == "dft":
        cls = "dft.UKS" if (args.method == "uhf" or args.spin != 0) else "dft.RKS"
        return (
            f"mf = {cls}(mol)\n"
            f'mf.xc = "{args.xc}"\n'
            "mf.kernel()  # runs the self-consistent field iterations"
        )
    cls = {"rhf": "scf.RHF", "uhf": "scf.UHF", "rohf": "scf.ROHF"}[args.method]
    return f"mf = {cls}(mol)\nmf.kernel()  # runs the self-consistent field iterations"


def _post_block(args):
    theory = getattr(args, "theory", "scf")
    if theory in ("scf", "dft"):
        return 'print(f"Total energy: {mf.e_tot:.10f} Hartree")'
    if theory == "mp2":
        return (
            "post = mp.MP2(mf)\n"
            "post.kernel()\n"
            'print(f"MP2 total energy: {post.e_tot:.10f} Hartree")'
        )
    if theory == "ccsd":
        return (
            "post = cc.CCSD(mf)\n"
            "post.kernel()\n"
            'print(f"CCSD total energy: {mf.e_tot + post.e_corr:.10f} Hartree")'
        )
    # ccsd_t
    return (
        "post = cc.CCSD(mf)\n"
        "post.kernel()\n"
        "et = post.ccsd_t()  # perturbative triples correction\n"
        'print(f"CCSD(T) total energy: {mf.e_tot + post.e_corr + et:.10f} Hartree")'
    )


def _not_included_note(args, flags):
    """One comment line per active flag the script does not reproduce."""
    active = [flag for flag, is_on in flags if is_on]
    if not active:
        return ""
    return (
        "\n# NOTE: the following pyscf-cli options are NOT included in this\n"
        f"# simplified script: {', '.join(active)}\n"
    )


def energy_script(args):
    note = _not_included_note(args, [
        ("--pes", getattr(args, "pes", False)),
        ("--mom", getattr(args, "mom", False)),
        ("--zpe", getattr(args, "zpe", False)),
        ("--decompose-total-energy", getattr(args, "decompose_total_energy", False)),
        ("--fixed-occ-decomp", getattr(args, "fixed_occ_decomp", False)),
        ("--occ-alpha/--occ-beta",
         getattr(args, "occ_alpha", None) is not None
         or getattr(args, "occ_beta", None) is not None),
    ])
    return "\n".join([
        HEADER + note,
        _imports(args),
        "",
        _mol_block(args),
        "",
        _reference_block(args),
        _post_block(args),
        "",
        "# MO energies (Hartree):",
        "print(mf.mo_energy)",
        "",
    ])


def relax_script(args):
    return "\n".join([
        HEADER,
        _imports(args, extra=["from pyscf.geomopt.geometric_solver import optimize"]),
        "",
        _mol_block(args),
        "",
        _reference_block(args),
        "",
        "mol_opt = optimize(mf)  # geometry optimization (geomeTRIC)",
        "",
        "# final single-point energy at the optimized geometry",
        _reference_block(args).replace("(mol)", "(mol_opt)"),
        _post_block(args),
        "",
        'print(mol_opt.tostring(format="xyz"))',
        "",
    ])


def vib_script(args):
    return "\n".join([
        HEADER,
        _imports(args, extra=["from pyscf.hessian import thermo"]),
        "",
        _mol_block(args),
        "",
        _reference_block(args),
        "",
        "hess = mf.Hessian().kernel()  # second derivatives of the energy",
        "vib = thermo.harmonic_analysis(mol, hess)",
        'print(vib["freq_wavenumber"])  # harmonic frequencies in cm^-1',
        "",
    ])


def thermo_script(args):
    return "\n".join([
        HEADER,
        _imports(args, extra=["from pyscf.hessian import thermo"]),
        "",
        _mol_block(args),
        "",
        _reference_block(args),
        "",
        "hess = mf.Hessian().kernel()",
        "vib = thermo.harmonic_analysis(mol, hess)",
        f'result = thermo.thermo(mf, vib["freq_au"], temperature={args.temp}, '
        f"pressure={args.pressure})",
        'print(result["G_tot"])  # Gibbs free energy (Hartree)',
        "",
    ])
