#!/usr/bin/env python3
"""Equivalent PySCF script generated by pyscf-cli --dry-run.

Run it with:  python3 this_script.py
Learn more:   https://pyscf.org/
"""

from pyscf import gto, scf, mp

mol = gto.M(
    atom="""
O      0.00000000     0.00000000     0.11730000
H      0.00000000     0.75720000    -0.46920000
H      0.00000000    -0.75720000    -0.46920000
""",
    basis="cc-pvdz",
    charge=0,
    spin=0,  # 2S = number of unpaired electrons
    unit="Angstrom",
)

mf = scf.RHF(mol)
mf.kernel()  # runs the self-consistent field iterations
post = mp.MP2(mf)
post.kernel()
print(f"MP2 total energy: {post.e_tot:.10f} Hartree")

# MO energies (Hartree):
print(mf.mo_energy)

